/*
 * generated by Xtext
 */
package msi.gama.lang.gaml.ide

import com.google.inject.Guice
import msi.gama.lang.gaml.GamlRuntimeModule
import msi.gama.lang.gaml.GamlStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class GamlIdeSetup extends GamlStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new GamlRuntimeModule, new GamlIdeModule))
	}
	
}
