/*
 * generated by Xtext
 */
package msi.gama.lang.gaml.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class GamlUiModule extends AbstractGamlUiModule {
}
