/*
 * generated by Xtext
 */
package msi.gama.lang.gaml.validation


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class GamlValidator extends AbstractGamlValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					GamlPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
}
