/*
 * generated by Xtext
 */
package msi.gama.lang.gaml.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import ummisco.gama.ui.modeling.internal.ModelingActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GamlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ModelingActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ModelingActivator.getInstance().getInjector(ModelingActivator.MSI_GAMA_LANG_GAML_GAML);
	}
	
}
